version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres 
      POSTGRES_USER: mahammad  
      POSTGRES_PASSWORD: 12312321 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
